version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  build:
    commands:
      - echo "Zipping app files..."
      - zip -r app.zip index.js package.json Procfile
      - echo "Uploading to S3..."
      - aws s3 cp app.zip s3://my-artifacts-azamcloud/app.zip
artifacts:
  files:
    - app.zip
