version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  build:
    commands:
      - echo "Creating app folder and copying files..."
      - mkdir -p app
      - cp index.js package.json Procfile app/
      - echo "Contents of app directory:"
      - ls -la app/

artifacts:
  base-directory: app
  files:
    - '**/*'
