version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2

  build:
    commands:
      - mkdir -p app
      - cp index.html app/
      - cp styles.css app/
      - cp script.js app/
      - echo "App folder contents:"
      - ls -la app/

artifacts:
  base-directory: app
  files:
    - '**/*'
