version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing Node.js dependencies..."
      - npm install

  build:
    commands:
      - echo "Zipping application..."
      - zip -r app.zip . -x "*.git*"

  post_build:
    commands:
      - echo "Uploading app.zip to S3..."
      - aws s3 cp app.zip s3://my-artifacts-azamcloud/app.zip
artifacts:
  files:
    - app.zip

